"""add image_url to trades

Revision ID: 0b702ee20c04
Revises: cebd25ab0d5d
Create Date: 2026-07-16 13:00:19.934261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b702ee20c04'
down_revision: Union[str, Sequence[str], None] = 'cebd25ab0d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'image_url')
    # ### end Alembic commands ###
