"""add_metaapi_fields

Revision ID: 14ecc833d71c
Revises: fe8a6fb996c3
Create Date: 2026-07-19 16:33:36.788205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ecc833d71c'
down_revision: Union[str, Sequence[str], None] = 'fe8a6fb996c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('metaapi_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('metaapi_account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'metaapi_account_id')
    op.drop_column('users', 'metaapi_token')
    # ### end Alembic commands ###
