"""add_mt5_fields

Revision ID: fe8a6fb996c3
Revises: 2a7f5d8a9d11
Create Date: 2026-07-19 16:12:53.422767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8a6fb996c3'
down_revision: Union[str, Sequence[str], None] = '2a7f5d8a9d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('mt5_account', sa.String(), nullable=True))
    op.create_index(op.f('ix_trades_external_id'), 'trades', ['external_id'], unique=True)
    op.add_column('users', sa.Column('mt5_api_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_mt5_api_key'), 'users', ['mt5_api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mt5_api_key'), table_name='users')
    op.drop_column('users', 'mt5_api_key')
    op.drop_index(op.f('ix_trades_external_id'), table_name='trades')
    op.drop_column('trades', 'mt5_account')
    op.drop_column('trades', 'external_id')
    # ### end Alembic commands ###
